on:
  workflow_dispatch:
  push:
    branches:
      - master  # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - run: pip install -U pip setuptools wheel && pip install ruamel.yaml
 
      - name: Convert YAML to JSON
        run: _scripts/yaml2json.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          enable_jekyll: true
          allow_empty_commit: true
